dist:   xenial
language: c
sudo: false
env:
    global:
        - secure: "$COVERITY_SCAN_TOKEN"

matrix:
    include:

#
# Whitespace check
#
    - env:
        - TEST="whitespace"
      script:
        - git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
        - git fetch upstream
        - git diff --check upstream/master

#
# Astyle check
#
    - env:
        - TEST="astyle"
      sudo: required
      install:
        - sudo apt-get install astyle
      script:
        - export ARTISTIC_STYLE_OPTIONS=".astylerc" && astyle `find . | egrep "\.c|\.h"` > astyle.out
        - TEST=$(cat astyle.out | grep Formatted | wc -l)
        - |
          if [[ $TEST -ne 0 ]]; then
            git --no-pager diff
            echo "Please fix style issues as shown above"
            exit 1
          fi

#
# gcc compile test
#
    - env:
        - TEST="gcc compile"
      compiler: gcc
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      install:
        - ./autogen.sh
      script:
        - ./configure
        - make

#
# clang compile test
#
    - env:
        - TEST="clang compile"
      compiler: clang
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      install:
        - ./autogen.sh
      script:
        - ./configure
        - make

#
# Coverity
#
    - env:
        - TEST="Coverity"
      compiler: gcc
      sudo: required
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
        coverity_scan:
            project:
                name: "$COVERITY_PROJECT"
                description: "Build submitted via Travis CI"
            notification_email: $COVERITY_EMAIL
            build_command_prepend: "./autogen.sh; ./configure; make clean"
            build_command:   "make"
            branch_pattern: $COVERITY_BRANCH
      script:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

#
# SonarCloud
#
    - env:
        - TEST="SonarCloud"
      compiler: clang
      sudo: required
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
        sonarcloud:
            organization: "libvmi"
            token:
                secure: "$SONAR_SCAN_TOKEN"
      install:
        - ./autogen.sh
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi'
        - ./configure
        - build-wrapper-linux-x86-64 --out-dir bw-output make -j2
        - sonar-scanner

#
# clang --analyze test
#
    - env:
        - TEST="clang --analyze"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-xenial-7.0
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      install:
        - ./autogen.sh
      script:
        - scan-build --status-bugs --use-cc=clang-7.0 ./configure
        - cd libvmi/config && make && cd ../..
        - scan-build --status-bugs --use-cc=clang-7.0 make

#
# debug test
#
    - env:
        - TEST="debug options enabled"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      before_install:
        - sed -i 's/#endif/#ifdef VMI_DEBUG\n#undef VMI_DEBUG\n#endif\n#define VMI_DEBUG __VMI_DEBUG_ALL\n#endif/g' libvmi/debug.h
      install:
        - ./autogen.sh
      script:
        - ./configure --enable-debug
        - make


#
# disable cache
#
    - env:
        - TEST="disable cache"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      install:
        - ./autogen.sh
      script:
        - ./configure --disable-address-cache --disable-page-cache
        - make

#
# without xenstore
#
    - env:
        - TEST="without xenstore"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      install:
        - ./autogen.sh
      script:
        - ./configure --without-xenstore
        - make

#
# disable config file
#
    - env:
        - TEST="disable libvmi.conf"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      install:
        - ./autogen.sh
      script:
        - ./configure --disable-config-file
        - make

#
# disable rekall profiles
#
    - env:
        - TEST="disable rekall profiles"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      install:
        - ./autogen.sh
      script:
        - ./configure --disable-rekall-profiles
        - make

#
# disable safety checks
#
    - env:
        - TEST="disable safety checks"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - bison
                - flex
                - check
                - libjson-c-dev
                - autoconf-archive
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      install:
        - ./autogen.sh
      script:
        - ./configure --disable-safety-checks
        - make
