dist:   xenial
language: c
sudo: false
env:
    global:
        - secure: "$COVERITY_SCAN_TOKEN"

matrix:
    include:

#
# Whitespace check
#
    - env:
        - TEST="whitespace"
      script:
        - git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
        - git fetch upstream
        - git diff --check upstream/master

#
# Astyle check
#
    - env:
        - TEST="astyle"
      sudo: required
      install:
        - sudo apt-get install astyle
      script:
        - export ARTISTIC_STYLE_OPTIONS=".astylerc" && astyle `find . | egrep "\.c$|\.h$"` > astyle.out
        - TEST=$(cat astyle.out | grep Formatted | wc -l)
        - |
          if [[ $TEST -ne 0 ]]; then
            git --no-pager diff
            echo "Please fix style issues as shown above"
            exit 1
          fi

#
# gcc compile test
#
    - env:
        - TEST="gcc compile and install"
      compiler: gcc
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=../install ..
        - make
        - make install

#
# clang compile test
#
    - env:
        - TEST="clang compile"
      compiler: clang
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      script:
        - mkdir build && cd build
        - cmake ..
        - make

#
# Coverity
#
    - env:
        - TEST="Coverity"
      compiler: gcc
      sudo: required
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
        coverity_scan:
            project:
                name: "$COVERITY_PROJECT"
                description: "Build submitted via Travis CI"
            notification_email: $COVERITY_EMAIL
            build_command_prepend: "mkdir build; cd build; cmake .."
            build_command:   "make"
            branch_pattern: $COVERITY_BRANCH
      script:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

#
# SonarCloud
#
    - env:
        - TEST="SonarCloud"
      compiler: clang
      sudo: required
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
        sonarcloud:
            organization: "libvmi"
            token:
                secure: "$SONAR_SCAN_TOKEN"
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi'
        - mkdir build && cd build
        - cmake ..
        - build-wrapper-linux-x86-64 --out-dir bw-output make -j2
        - sonar-scanner

#
# clang --analyze test
#
    - env:
        - TEST="clang --analyze"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-xenial-7.0
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      script:
        - mkdir build && cd build
        - cmake ..
        - make static_analysis_test

#
# debug test
#
    - env:
        - TEST="debug options enabled"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      before_install:
        - sed -i 's/#endif/#ifdef VMI_DEBUG\n#undef VMI_DEBUG\n#endif\n#define VMI_DEBUG __VMI_DEBUG_ALL\n#endif/g' libvmi/debug.h
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=DEBUG ..
        - make


#
# disable cache
#
    - env:
        - TEST="disable cache"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      script:
        - mkdir build && cd build
        - cmake -DENABLE_ADDRESS_CACHE=OFF -DENABLE_PAGE_CACHE=OFF ..
        - make

#
# without xenstore
#
    - env:
        - TEST="without xenstore"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      script:
        - mkdir build && cd build
        - cmake -DENABLE_XENSTORE=OFF ..
        - make

#
# disable config file
#
    - env:
        - TEST="disable libvmi.conf"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      script:
        - mkdir build && cd build
        - cmake -DENABLE_CONFIGFILE=OFF -DBUILD_EXAMPLES=OFF ..
        - make

#
# disable rekall profiles
#
    - env:
        - TEST="disable rekall profiles"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      script:
        - mkdir build && cd build
        - cmake -DREKALL_PROFILES=OFF -DBUILD_EXAMPLES=OFF ..
        - make

#
# disable safety checks
#
    - env:
        - TEST="disable safety checks"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      script:
        - mkdir build && cd build
        - cmake -DENABLE_SAFETY_CHECKS=OFF ..
        - make

#
# release build
#
    - env:
        - TEST="release build"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=RELEASE ..
        - make

#
# cross-compile for ARM
#
    - env:
        - TEST="cross-compile for ARM"
      addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - cmake
                - bison
                - flex
                - check
                - libjson-c-dev
                - libvirt-dev
                - libxen-dev
                - libfuse-dev
                - gcc-arm-linux-gnueabi
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/arm-gcc.cmake ..
        - make
